from mongoengine import Document, StringField, DateField, EmailField, URLField

class Opportunity(Document):
    notice_id = StringField(max_length=255, unique=True)
    title = StringField(max_length=255)
    solicitation_number = StringField(max_length=255, blank=True, null=True)
    department = StringField(max_length=255, blank=True, null=True)
    sub_tier = StringField(max_length=255, blank=True, null=True)
    office = StringField(max_length=255, blank=True, null=True)
    posted_date = DateField(blank=True, null=True)
    opportunity_type = StringField(max_length=255, blank=True, null=True)
    base_type = StringField(max_length=255, blank=True, null=True)
    archive_type = StringField(max_length=255, blank=True, null=True)
    archive_date = DateField(blank=True, null=True)
    naics_code = StringField(max_length=255, blank=True, null=True)
    classification_code = StringField(max_length=255, blank=True, null=True)
    active = StringField(max_length=255, blank=True, null=True)
    award_date = DateField(blank=True, null=True)
    award_number = StringField(max_length=255, blank=True, null=True)
    award_amount = StringField(max_length=255, blank=True, null=True)
    awardee_name = StringField(max_length=255, blank=True, null=True)
    awardee_street_address = StringField(max_length=255, blank=True, null=True)
    awardee_city = StringField(max_length=255, blank=True, null=True)
    awardee_state = StringField(max_length=255, blank=True, null=True)
    awardee_zip = StringField(max_length=255, blank=True, null=True)
    awardee_country = StringField(max_length=255, blank=True, null=True)
    awardee_ueiSAM = StringField(max_length=255, blank=True, null=True)
    point_of_contact_email = EmailField(blank=True, null=True)
    point_of_contact_phone = StringField(max_length=255, blank=True, null=True)
    point_of_contact_name = StringField(max_length=255, blank=True, null=True)
    description = StringField(blank=True, null=True)
    organization_type = StringField(max_length=255, blank=True, null=True)
    office_zipcode = StringField(max_length=255, blank=True, null=True)
    office_city = StringField(max_length=255, blank=True, null=True)
    office_state = StringField(max_length=255, blank=True, null=True)
    office_country_code = StringField(max_length=255, blank=True, null=True)
    place_of_performance_street_address = StringField(max_length=255, blank=True, null=True)
    place_of_performance_city = StringField(max_length=255, blank=True, null=True)
    place_of_performance_state = StringField(max_length=255, blank=True, null=True)
    place_of_performance_zip = StringField(max_length=255, blank=True, null=True)
    place_of_performance_country = StringField(max_length=255, blank=True, null=True)
    ui_link = URLField(blank=True, null=True)
    additional_info_link = URLField(blank=True, null=True)

# import mongoengine as me

# class Opportunity(me.Document):
#     notice_id = me.StringField(required=True, unique=True)
#     title = me.StringField()
#     solicitation_number = me.StringField()
#     department = me.StringField()
#     sub_tier = me.StringField()
#     office = me.StringField()
#     posted_date = me.StringField()
#     opportunity_type = me.StringField()
#     base_type = me.StringField()
#     archive_type = me.StringField()
#     archive_date = me.StringField()
#     naics_code = me.StringField()
#     classification_code = me.StringField()
#     active = me.StringField()
#     award_date = me.StringField()
#     award_number = me.StringField()
#     award_amount = me.StringField()
#     awardee_name = me.StringField()
#     awardee_street_address = me.StringField()
#     awardee_city = me.StringField()
#     awardee_state = me.StringField()
#     awardee_zip = me.StringField()
#     awardee_country = me.StringField()
#     awardee_ueiSAM = me.StringField()
#     point_of_contact_email = me.StringField()
#     point_of_contact_phone = me.StringField()
#     point_of_contact_name = me.StringField()
#     description = me.StringField()
#     organization_type = me.StringField()
#     office_zipcode = me.StringField()
#     office_city = me.StringField()
#     office_state = me.StringField()
#     office_country_code = me.StringField()
#     place_of_performance_street_address = me.StringField()
#     place_of_performance_city = me.StringField()
#     place_of_performance_state = me.StringField()
#     place_of_performance_zip = me.StringField()
#     place_of_performance_country = me.StringField()
#     ui_link = me.StringField()
#     additional_info_link = me.StringField()