# from django.db import models

# class Opportunity(models.Model):
#     notice_id = models.CharField(max_length=255, unique=True)
#     title = models.CharField(max_length=255)
#     solicitation_number = models.CharField(max_length=255, blank=True, null=True)
#     department = models.CharField(max_length=255, blank=True, null=True)
#     sub_tier = models.CharField(max_length=255, blank=True, null=True)
#     office = models.CharField(max_length=255, blank=True, null=True)
#     posted_date = models.DateField(blank=True, null=True)
#     opportunity_type = models.CharField(max_length=255, blank=True, null=True)
#     base_type = models.CharField(max_length=255, blank=True, null=True)
#     archive_type = models.CharField(max_length=255, blank=True, null=True)
#     archive_date = models.DateField(blank=True, null=True)
#     naics_code = models.CharField(max_length=255, blank=True, null=True)
#     classification_code = models.CharField(max_length=255, blank=True, null=True)
#     active = models.CharField(max_length=255, blank=True, null=True)
#     award_date = models.DateField(blank=True, null=True)
#     award_number = models.CharField(max_length=255, blank=True, null=True)
#     award_amount = models.CharField(max_length=255, blank=True, null=True)
#     awardee_name = models.CharField(max_length=255, blank=True, null=True)
#     awardee_street_address = models.CharField(max_length=255, blank=True, null=True)
#     awardee_city = models.CharField(max_length=255, blank=True, null=True)
#     awardee_state = models.CharField(max_length=255, blank=True, null=True)
#     awardee_zip = models.CharField(max_length=255, blank=True, null=True)
#     awardee_country = models.CharField(max_length=255, blank=True, null=True)
#     awardee_ueiSAM = models.CharField(max_length=255, blank=True, null=True)
#     point_of_contact_email = models.EmailField(blank=True, null=True)
#     point_of_contact_phone = models.CharField(max_length=255, blank=True, null=True)
#     point_of_contact_name = models.CharField(max_length=255, blank=True, null=True)
#     description = models.TextField(blank=True, null=True)
#     organization_type = models.CharField(max_length=255, blank=True, null=True)
#     office_zipcode = models.CharField(max_length=255, blank=True, null=True)
#     office_city = models.CharField(max_length=255, blank=True, null=True)
#     office_state = models.CharField(max_length=255, blank=True, null=True)
#     office_country_code = models.CharField(max_length=255, blank=True, null=True)
#     place_of_performance_street_address = models.CharField(max_length=255, blank=True, null=True)
#     place_of_performance_city = models.CharField(max_length=255, blank=True, null=True)
#     place_of_performance_state = models.CharField(max_length=255, blank=True, null=True)
#     place_of_performance_zip = models.CharField(max_length=255, blank=True, null=True)
#     place_of_performance_country = models.CharField(max_length=255, blank=True, null=True)
#     ui_link = models.URLField(blank=True, null=True)
#     additional_info_link = models.URLField(blank=True, null=True)
