# Generated by Django 4.2.5 on 2024-05-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('solicitation_number', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_tier', models.CharField(blank=True, max_length=255, null=True)),
                ('office', models.CharField(blank=True, max_length=255, null=True)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('opportunity_type', models.CharField(blank=True, max_length=255, null=True)),
                ('base_type', models.CharField(blank=True, max_length=255, null=True)),
                ('archive_type', models.CharField(blank=True, max_length=255, null=True)),
                ('archive_date', models.DateField(blank=True, null=True)),
                ('naics_code', models.CharField(blank=True, max_length=255, null=True)),
                ('classification_code', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.CharField(blank=True, max_length=255, null=True)),
                ('award_date', models.DateField(blank=True, null=True)),
                ('award_number', models.CharField(blank=True, max_length=255, null=True)),
                ('award_amount', models.CharField(blank=True, max_length=255, null=True)),
                ('awardee_name', models.CharField(blank=True, max_length=255, null=True)),
                ('awardee_street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('awardee_city', models.CharField(blank=True, max_length=255, null=True)),
                ('awardee_state', models.CharField(blank=True, max_length=255, null=True)),
                ('awardee_zip', models.CharField(blank=True, max_length=255, null=True)),
                ('awardee_country', models.CharField(blank=True, max_length=255, null=True)),
                ('awardee_ueiSAM', models.CharField(blank=True, max_length=255, null=True)),
                ('point_of_contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('point_of_contact_phone', models.CharField(blank=True, max_length=255, null=True)),
                ('point_of_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('organization_type', models.CharField(blank=True, max_length=255, null=True)),
                ('office_zipcode', models.CharField(blank=True, max_length=255, null=True)),
                ('office_city', models.CharField(blank=True, max_length=255, null=True)),
                ('office_state', models.CharField(blank=True, max_length=255, null=True)),
                ('office_country_code', models.CharField(blank=True, max_length=255, null=True)),
                ('place_of_performance_street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('place_of_performance_city', models.CharField(blank=True, max_length=255, null=True)),
                ('place_of_performance_state', models.CharField(blank=True, max_length=255, null=True)),
                ('place_of_performance_zip', models.CharField(blank=True, max_length=255, null=True)),
                ('place_of_performance_country', models.CharField(blank=True, max_length=255, null=True)),
                ('ui_link', models.URLField(blank=True, null=True)),
                ('additional_info_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
